# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Global
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
  HELM_REPO: https://chartmuseum.magentahosted.dk
  # REVIEW_VERSION is used by the config-updater in salt-automation. Make sure to keep them synchronised!
  REVIEW_VERSION: 0.0.0-mr$CI_MERGE_REQUEST_IID
  REVIEW_CHART_URL: $HELM_REPO/api/charts/os2mo/$REVIEW_VERSION
  REVIEW_URL: https://review-chart-mr$CI_MERGE_REQUEST_IID.moraci.magentahosted.dk

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .venv/
    - .cache/pip
    - .cache/pre-commit

stages:
  - lint
  - test
  - review
  - release
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID

include:
  - project: 'labs/salt-automation'
    ref: 'master'
    file: '/gitlab-ci-templates/common/autopub.v1.yml'
  - project: "labs/salt-automation"
    ref: "master"
    file: "/gitlab-ci-templates/common/config-updater-meta.v1.yml"

# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------
.install-deps-template: &install-deps
  before_script:
    # Install pre-commit
    - pip install pre-commit
    # Install yamllint
    - pip install yamllint
    # Install shellcheck
    - apt-get update && apt-get install -y shellcheck
    # Install Helm
    - curl https://baltocdn.com/helm/signing.asc | apt-key add -
    - apt-get update && apt-get install -y apt-transport-https coreutils
    - |-
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" |
        tee /etc/apt/sources.list.d/helm-stable-debian.list
    - apt-get update && apt-get install -y helm
    - curl -sL https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz | tar xz -C /usr/bin/

.lint-template: &lint
  <<: *install-deps
  image: python:3.8
  stage: lint

.test-template: &test
  <<: *install-deps
  image: python:3.8
  stage: test

# ---------------------------------------------------------------------------
# Lint
# ---------------------------------------------------------------------------
Lint Project:
  <<: *lint
  script:
    - pre-commit run --all-files

Lint Chart:
  stage: lint
  image: quay.io/helmpack/chart-testing:v3.4.0
  script:
    - ct lint --all --chart-dirs .


# ---------------------------------------------------------------------------
# Test
# ---------------------------------------------------------------------------
Generate Project:
  <<: *test
  script:
    - helm template --kube-version 1.19.11 os2mo
    - helm template --kube-version 1.19.11 os2mo | kubeval --schema-location https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master -


Release local:
  stage: release
  needs: []
  image:
    name: alpine/helm:3.9.0
    entrypoint: [""]
  tags:
    - docker
  before_script:
    - helm registry login --username ${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY_IMAGE}
  script:
    - helm package --version=0.0.0-${CI_COMMIT_SHA} os2mo
    - helm push os2mo-0.0.0-${CI_COMMIT_SHA}.tgz oci://${CI_REGISTRY_IMAGE}/helm-charts/


Release version:
  stage: release
  needs: []
  image:
    name: alpine/helm:3.7.1
    entrypoint: [""]
  tags:
    - docker
  before_script:
    - helm plugin install https://github.com/chartmuseum/helm-push.git
    - helm repo add magenta-chartmuseum $HELM_REPO
  script:
    - helm cm-push --version=$CI_COMMIT_TAG os2mo magenta-chartmuseum
  rules:
    - if: $CI_COMMIT_TAG =~ /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/


pages:
  image: python:3.8
  stage: release
  needs: []
  before_script:
    - pip install mkdocs-material
    - pip install mkdocs-autorefs
  script:
    - mkdocs build --strict --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG =~ /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/

# Review Stage
##############
deploy_helm_chart:
  stage: review
  needs: []
  image:
    name: alpine/helm:3.7.1
    entrypoint: [""]
  tags:
    - docker
  before_script:
    - helm plugin install https://github.com/chartmuseum/helm-push.git
    - helm repo add magenta-chartmuseum $HELM_REPO
  script:
    - helm cm-push --version=$REVIEW_VERSION --force os2mo magenta-chartmuseum
  environment:
    name: chart/$CI_MERGE_REQUEST_IID
    url: $REVIEW_CHART_URL
    on_stop: stop_helm_chart
    auto_stop_in: 1 week
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
      allow_failure: true

stop_helm_chart:
  stage: review
  needs: []
  image: alpine:3
  variables:
    GIT_STRATEGY: none # We do not need the source code
  tags:
    - docker
  before_script:
    - apk add curl
  script:
    - curl -X DELETE -u $HELM_REPO_USERNAME:$HELM_REPO_PASSWORD $REVIEW_CHART_URL
  environment:
    name: chart/$CI_MERGE_REQUEST_IID
    action: stop
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
      allow_failure: true

Deploy Review:
  stage: review
  needs: ["deploy_helm_chart"]
  image: debian:bullseye
  variables:
    GIT_STRATEGY: none # We do not need the source code
  tags:
    - deploy
  before_script:
    - apt-get update && apt-get install -y curl jq
  script:
    - curl --silent --fail --request POST --user $CONFIG_UPDATER_REVIEW_APP_USERNAME:$CONFIG_UPDATER_REVIEW_APP_PASSWORD "https://config-updater.magentahosted.dk/os2mo/review-apps/chart/deploy?mr_id=$CI_MERGE_REQUEST_IID"
    - until $(curl "${REVIEW_URL}/version/" | jq ".mo_hash == \"$CI_COMMIT_SHA\""); do sleep 5; done
  environment:
    name: review/$CI_MERGE_REQUEST_IID
    url: $REVIEW_URL
    on_stop: Stop Review
    auto_stop_in: 1 week
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
      allow_failure: true

Stop Review:
  stage: review
  needs: []
  image: curlimages/curl:7.81.0
  variables:
    GIT_STRATEGY: none # We do not need the source code
  tags:
    - deploy
  script:
    - curl --silent --fail --request POST --user $CONFIG_UPDATER_REVIEW_APP_USERNAME:$CONFIG_UPDATER_REVIEW_APP_PASSWORD "https://config-updater.magentahosted.dk/os2mo/review-apps/chart/undeploy?mr_id=$CI_MERGE_REQUEST_IID"
  environment:
    name: review/$CI_MERGE_REQUEST_IID
    action: stop
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
      allow_failure: true


# Release stage
###############

Release to Dev:
  extends: .release-to-dev
  needs: ["Release version"]
  variables:
    ENDPOINT: os2mo/flux/helm/update-dev

Release to Test:
  extends: .release-to-test
  needs: []
  variables:
    ENDPOINT: os2mo/flux/helm/update-test

Release to Prod:
  extends: .release-to-prod
  needs: []
  variables:
    ENDPOINT: os2mo/flux/helm/update-prod
