# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dipex-deployment
  labels:
    app: dipex
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 0
  selector:
    matchLabels:
      app: dipex
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dipex
    spec:
      containers:
        - name: dipex
          image: "{{ .Values.dipex.image.repository }}:{{ .Values.dipex.image.tag }}"
          imagePullPolicy: {{ .Values.dipex.image.pullPolicy }}
          command: ["sleep"]
          args: ["infinity"]
          env:
            - name: CLIENT_ID
              value: "dipex"
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-dipex-secret
                  key: client_secret
            - name: AUTH_SERVER
              value: "http://keycloak-service:8080/auth"
          volumeMounts:
            - name: settingsfile
              mountPath: "./opt/settings"
              readOnly: true
            - name: secretsfile
              mountPath: "./opt/secrets"
              readOnly: true
          resources:
            {{- toYaml .Values.dipex.resources | nindent 12 }}
      volumes:
        - name: settingsfile
          configMap:
            name: dipex-config
        - name: secretsfile
          secret:
            secretName: dipex-secret
      restartPolicy: Always
