# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: v1
kind: Secret
metadata:
  name: mox-db-secret
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{ if .Values.database.external }}
stringData:
  db_password: {{ .Values.database.password }}
{{ else }}
    secret-generator.v1.mittwald.de/autogenerate: db_password
data: {}
{{ end }}
