# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{ if .Values.database.external }}
{{ else }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mox-db-deployment
  labels:
    app: mox-db
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mox-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mox-db
    spec:
      containers:
        - name: mox-db
          image: postgres:11
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{ if .Values.database.password_secret }}
                  name: {{ .Values.database.password_secret }}
                  {{ else }}
                  name: mox-db-secret
                  {{ end }}
                  key: db_password
          ports:
            - containerPort: 5432
          resources:
            {{- toYaml .Values.database.resources | nindent 12 }}
      restartPolicy: Always
{{ end }}
