# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.orgviewer.adm.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orgviewer-adm-ingress
spec:
  {{ if .Values.orgviewer.adm.ingress.tls_secret }}
  tls:
    - hosts:
       - {{ .Values.orgviewer.adm.ingress.hostname }}
      secretName: {{ .Values.orgviewer.adm.ingress.tls_secret }}
  {{ end }}
  rules:
    - host: {{ .Values.orgviewer.adm.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orgviewer-adm-service
                port:
                  number: 80
{{- end }}
