# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.os2sync.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: os2sync
  labels:
    app: os2sync
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: os2sync
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: os2sync
    spec:
      containers:
        - name: os2sync
          image: "{{ .Values.os2sync.image.registry }}/{{ .Values.os2sync.image.repository }}:{{ .Values.os2sync.image.tag }}"
          env:
            - name: ClientSettings__WscKeystoreLocation
              value: "/certificate/certificate.p12"
            - name: ClientSettings__WscKeystorePassword
              valueFrom:
                secretKeyRef:
                  name: os2sync-secret
                  key: client_cert_password
            - name: DisableRevocationCheck
              value: {{ .Values.os2sync.disable_revocation_check | quote }}
            - name: LogSettings__LogRequestResponse
              value: {{ .Values.os2sync.log_request_response | quote }}
            - name: CVR
              value: {{ required "The Municipality ENV is missing" .Values.os2sync.municipality | quote }}
            - name: SchedulerSettings__Enabled
              value: {{ .Values.os2sync.enable_scheduler | quote }}
            - name: ServiceSettings__WspCertificateLocation
              value: "/trust/organisation.cer"
            - name: StsSettings__StsCertificateLocation
              value: "/trust/sts.cer"
            # Although "TrustAllCertificates" sounds ominous it's not that bad.
            # The above certificates are used for validation, this flag only disables 
            # verifying root CA for those certificates.
            # OS2sync does not currently work without this flag enabled
            - name: TrustAllCertificates
              value: "true"
            - name: Environment
              value: {{ .Values.os2sync.environment | quote }}
            - name: LogSettings__LogLevel
              value: {{ .Values.os2sync.log_level | quote }}
            - name: SchedulerSettings__DBType
              value: MYSQL
            - name: DB_HOST
              value: {{ required "The OS2sync DB_HOST ENV is missing" .Values.os2sync.db_host | quote }}
            - name: DB_NAME
              value: {{ .Values.os2sync.db_name | quote }}
            - name: DB_USERNAME
              value: {{ .Values.os2sync.db_username | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: os2sync-secret
                  key: db_password
            - name: SchedulerSettings__DBConnectionString
              value: "server=$(DB_HOST);user id=$(DB_USERNAME);password=$(DB_PASSWORD);database=$(DB_NAME);persistsecurityinfo=True"
            - name: PassiverAndReImportOnErrors
              value: {{ .Values.os2sync.os2sync_passiver_and_re_import_on_errors | default "false" | quote }}
          ports:
            - containerPort: 5000
          resources:
            {{- toYaml .Values.os2sync.resources | nindent 12 }}
          volumeMounts:
            - name: certificate-volume
              readOnly: true
              mountPath: "/certificate"
            - name: trust
              readOnly: true
              mountPath: "/trust"
      volumes:
        - name: trust
          configMap:
            name: trust-config
            items: 
            {{ if eq .Values.os2sync.environment "PROD" }}
              - key: prod-org.cer
                path: organisation.cer
              - key: prod-sts.cer
                path: sts.cer
            {{ else if eq .Values.os2sync.environment "TEST" }}
              - key: test-org.cer
                path: organisation.cer
              - key: test-sts.cer
                path: sts.cer
            {{ else }}
              {{- fail ".Values.os2sync.environment must be set to either TEST or PROD" }}
            {{ end }}
        - name: certificate-volume
          secret:
            secretName: os2sync-certificate-secret
{{- end }}
