# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.os2sync.enabled }}
{{- $keycloak_client_id := "integration_os2sync_export" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: os2sync-export
  labels:
    app: os2sync-export
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: os2sync-export
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: os2sync-export
    spec:
      containers:
        - name: os2sync-export
          image: "{{ .Values.os2sync.exporter.registry }}/{{ .Values.os2sync.exporter.repository }}:{{ .Values.os2sync.exporter.tag }}"
          env:
            - name: Municipality
              value: {{ required "The Municipality ENV is missing" .Values.os2sync.municipality | quote }}
            - name: FASTRAMQPI__MO_URL
              value:  "http://mo-service:5000"
            - name: FASTRAMQPI__AUTH_SERVER
              value: "http://keycloak-service:8080/auth"
            - name: FASTRAMQPI__AMQP__URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.amqp.url_secret }}
                  key: url
            - name: FASTRAMQPI__AUTH_REALM
              value: "mo"
            - name: FASTRAMQPI__CLIENT_ID
              value: "{{ $keycloak_client_id }}"
            - name: FASTRAMQPI__CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: os2sync-export-client-secret
                  key: client_secret
            # TODO: Remove the following section when os2sync_export is upgraded past version 6 everywhere
            - name: MO_URL
              value:  "http://mo-service:5000"
            - name: LOG_LEVEL
              value: {{ .Values.os2sync.os2sync_log_level | default "INFO" | quote }}
            - name: GRAPHQL_TIMEOUT
              value: {{ .Values.os2sync.graphql_timeout | default "300"| quote }}
            - name: AUTH_SERVER
              value: "http://keycloak-service:8080/auth"
            - name: AMQP__URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.amqp.url_secret }}
                  key: url
            - name: AUTH_REALM
              value: "mo"
            - name: CLIENT_ID
              value: "{{ $keycloak_client_id }}"
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: os2sync-export-client-secret
                  key: client_secret
            # end of legacy settings section - Delete to here.
            - name: os2sync_api_url
              value: {{ .Values.os2sync.os2sync_api_url| default "http://os2sync-service:5000/api" | quote }}
            {{- if .Values.os2sync.extraEnv }}
            {{ toYaml .Values.os2sync.extraEnv | indent 12 | trim }}
            {{- end }}
            {{ if .Values.sentry.environment }}
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sentry.secret }}
                  key: dsn
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.sentry.environment | quote }}
            {{ end }}
          ports:
            - containerPort: 8000
          resources:
            {{- toYaml .Values.os2sync.resources | nindent 12 }}
      initContainers:
        {{ include "os2mo.wait-for-keycloak" . | nindent 8 }}
        {{ include "os2mo.wait-for-mo" . | nindent 8 }}
        - name: create-client-secret
          image: "{{ .Values.keycloak.integrationbuilder.image.registry }}/{{ .Values.keycloak.integrationbuilder.image.repository }}:{{ .Values.keycloak.integrationbuilder.image.tag }}"
          env:
            {{ include "os2mo.keycloak_terraform_db_connection" .  | nindent 12 }}
            - name: POSTGRES_SCHEMA_NAME
              value: terraform_remote_state_os2sync_export

            # Keycloak REST connection
            - name: TF_VAR_admin_password
              valueFrom:
                secretKeyRef:
                  name: {{ include "os2mo.keycloak_admin_secret" . }}
                  key: admin_password

            # Configuration of the client
            - name: TF_VAR_client_name
              value: {{ $keycloak_client_id }}
            - name: TF_VAR_client_roles
              value: '["reader", "service_api"]'
            - name: TF_VAR_client_secret
              valueFrom:
                secretKeyRef:
                  name: os2sync-export-client-secret
                  key: client_secret
            - name: TF_VAR_client_uuid
              value: "0525711c-baad-c0de-006f-733273796e63"

          resources:
            {{- toYaml .Values.initContainers.resources | nindent 12 }}
        - name: os2mo-init
          image: "{{ .Values.os2mo.init.image.registry }}/{{ .Values.os2mo.init.image.repository }}:{{ .Values.os2mo.init.image.tag }}"
          env:
            - name: MO_URL
              value: "http://mo-service:5000"
            - name: AUTH_SERVER
              value: "http://keycloak-service:8080/auth"
            - name: AUTH_REALM
              value: "mo"
            - name: CLIENT_ID
              value: "dipex"
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-dipex-secret
                  key: client_secret
            - name: LOG_LEVEL
              value: {{ .Values.os2mo.init.log_level | quote }}
          resources:
            {{- toYaml .Values.initContainers.resources | nindent 12 }}
          volumeMounts:
           - name: os2sync-export-init-config-volume
             mountPath: /config
             readOnly: true
      volumes:
        - name: os2sync-export-init-config-volume
          configMap:
            name: os2sync-export-init-config
            items:
              - key: config
                path: config.yml
          
{{- end }}
