# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.os2sync.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: os2sync-export-init-config
  labels:
    app: os2sync-export
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config: |
    facets:
      org_unit_address_type:
        contact:
          title: "Henvendelsessted"
          scope: "TEXT"
        location:
          title: "Lokation"
          scope: "TEXT"
{{- end }}
