# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mo-deployment
  labels:
    app: mo
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.os2mo.replicaCount }}
  selector:
    matchLabels:
      app: mo
  strategy:
    type: {{ .Values.os2mo.strategy }}
  template:
    metadata:
      labels:
        app: mo
    spec:
      {{- if not (empty .Values.os2mo.image.pullSecret) }}
      imagePullSecrets:
        - name: {{ .Values.os2mo.image.pullSecret }}
      {{- end }}
      containers:
        - name: mo
          {{- if and (ne .Values.os2mo.image.tag "latest") (contains "." .Values.os2mo.image.tag) }}
            {{- if and (.Values.os2mo.probes.enabled) (semverCompare "<3.24.0" .Values.os2mo.image.tag) }}
              {{- fail "MO version must be at least 3.24.0 when probes are enabled" }}
            {{- end }}
          {{- end }}
          image: "{{ .Values.os2mo.image.registry }}/{{ .Values.os2mo.image.repository }}:{{ .Values.os2mo.image.tag }}"
          imagePullPolicy: {{ .Values.os2mo.image.pullPolicy }}
          env:
            - name: PORT
              value: "5000"

            # Disable service platformen
            - name: DUMMY_MODE
              value: "true"

            - name: LORA_URL
              value: "http://mox-service:8080/"

            # AMQP
            {{- if .Values.amqp.enabled }}
            {{- if and (ne .Values.os2mo.image.tag "latest") (contains "." .Values.os2mo.image.tag) }}
              {{- if (semverCompare "<4.5.0" .Values.os2mo.image.tag) }}
                {{- fail "MO version must be at least 4.5.0 when AMQP is enabled" }}
              {{ end }}
            {{- else }}
            {{ if .Values.amqp.scheme }}
            - name: AMQP_SCHEME
              value: "{{ .Values.amqp.scheme }}"
            {{ end }}
            - name: AMQP_HOST
              value: "{{ .Values.amqp.host }}"
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: mo-amqp-user
                  key: name
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mo-amqp-user
                  key: password
            {{ if .Values.amqp.port }}
            - name: AMQP_PORT
              value: "{{ .Values.amqp.port }}"
            {{ end }}
            - name: AMQP_VHOST
              value: "{{ .Values.amqp.vhost }}"
            {{ if .Values.amqp.exchange }}
            - name: AMQP_EXCHANGE
              value: "{{ .Values.amqp.exchange }}"
            {{ end }}
            {{- end }}
            {{- end }}

            # Confdb
            - name: CONF_DB_USE
              value: "false"

            - name: TESTCAFE_ENABLE
              value: "false"

            # gunicorn MAX_WORKERS
            - name: MAX_WORKERS
              value: "{{ .Values.os2mo.gunicorn.max_workers }}"

            # Keycloak
            - name: KEYCLOAK_SCHEMA
              value: http
            - name: KEYCLOAK_PORT
              value: "8080"
            - name: KEYCLOAK_HOST
              value: "keycloak-service"
            {{- $is_http := empty .Values.ingress.tls_secret }}
            {{- $protocol := ternary "http" "https" $is_http }}
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: "{{ $protocol }}://{{ .Values.ingress.hostname }}/auth/"
            - name: KEYCLOAK_MO_CLIENT
              value: "mo-frontend"

            - name: CONFDB_SHOW_ORG_UNIT_BUTTON
              value: {{ .Values.sdtool.enabled | quote }}
          envFrom:
{{ if .Values.os2mo.external_env_config_map_name }}
          - configMapRef:
              name: "{{ .Values.os2mo.external_env_config_map_name }}"
{{ end }}
          - configMapRef:
              name: mo-config
          - configMapRef:
              name: mo-json-config

          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: "/queries"
              name: queries-pv-storage
          resources:
            {{- toYaml .Values.os2mo.resources | nindent 12 }}
          {{- if .Values.os2mo.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5000
            periodSeconds: {{ .Values.os2mo.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.os2mo.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.os2mo.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5000
            periodSeconds: {{ .Values.os2mo.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.os2mo.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.os2mo.probes.readiness.failureThreshold }}
          startupProbe:
            httpGet:
              path: /health/ready
              port: 5000
            failureThreshold: {{ .Values.os2mo.probes.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.os2mo.probes.startupProbe.periodSeconds }}
          {{- end }}
      initContainers:
        {{ include "os2mo.wait-for-keycloak" . | nindent 8 }}
        {{ include "os2mo.wait-for-mox" . | nindent 8 }}
        {{- if .Values.sdtool.enabled }}
        {{ include "os2mo.wait-for-sdtool" . | nindent 8 }}
        {{- end }}
      volumes:
        - name: queries-pv-storage
          persistentVolumeClaim:
            claimName: mo-queries-pv-claim
      restartPolicy: Always
