# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mo-ingress
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{ if ne .Values.ingress.class "" }}
  ingressClassName: {{ .Values.ingress.class }}
  {{ end }}
  {{ if .Values.ingress.tls_secret }}
  tls:
    - hosts:
       - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.tls_secret }}
  {{ end }}
  rules:
    - http:
        paths:
          {{- range tuple "/openapi.json" "/graphql" "/metrics" "/docs" "/service/" "/version/" "/health/" }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: mo-service
                port:
                  number: 5000
          {{- end }}
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port:
                  number: 8080
          {{ if not .Values.os2mo.headless }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mo-frontend-service
                port:
                  number: 80
          {{ end }}
  {{ if .Values.ingress.hostname }}
      host: {{ .Values.ingress.hostname }}
  {{ end }}
