---
# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
{{- if .Values.orgviewer.adm.enabled }}
{{- $keycloak_client_id := "integration_orgviewer_adm" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orgviewer-adm-deployment
  labels:
    app: orgviewer-adm
spec:
  replicas: {{ .Values.orgviewer.adm.replicaCount }}
  selector:
    matchLabels:
      app: orgviewer-adm
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: orgviewer-adm
    spec:
      containers:
        - name: orgviewer-adm
          {{- if and (ne .Values.orgviewer.image.tag "latest") (contains "." .Values.orgviewer.image.tag) }}
            {{- if (semverCompare "<2.3.0" .Values.orgviewer.image.tag) }}
              {{- fail "Orgviewer version must be at least 2.3.0" }}
            {{- end }}
          {{- end }}
          image: "{{ .Values.orgviewer.image.repository }}:{{ .Values.orgviewer.image.tag }}"
          imagePullPolicy: {{ .Values.orgviewer.image.pullPolicy }}
          env:
            {{- if not .Values.orgviewer.adm.url }}
              {{- fail ".Values.orgviewer.adm.url must be set" }}
            {{- end }}
            {{- if not .Values.orgviewer.adm.title }}
              {{- fail ".Values.orgviewer.adm.title must be set" }}
            {{- end }}
            {{- if not .Values.orgviewer.adm.org_uuid }}
              {{- fail ".Values.orgviewer.adm.org_uuid must be set" }}
            {{- end }}

            - name: GLOBAL_API_URL
              value: {{ .Values.orgviewer.adm.url }}

            - name: GLOBAL_APP_TITLE
              value: {{ .Values.orgviewer.adm.title }}

            - name: GLOBAL_API_ROOT_UUID
              value: {{ .Values.orgviewer.adm.org_uuid }}

            - name: KEYCLOAK_CLIENT_ID
              value: {{ $keycloak_client_id }}

            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: orgviewer-adm-client-secret
                  key: client_secret

            - name: KEYCLOAK_BASEURL
              value: "http://keycloak-service:8080/auth"

            - name: PROXY_PASS_TO
              value: "http://mo-service:5000"

            - name: GLOBAL_ORG_PERSON_RELATION
              value: "engagement"

            - name: CUSTOMER
              value: "default"

            - name: VUE_APP_TREE_LAYOUT
              value: "vertical"
          envFrom:
            - configMapRef:
                name: orgviewer-environment-config
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.orgviewer.adm.resources | nindent 12 }}
      initContainers:
        {{ include "os2mo.wait-for-keycloak" . | nindent 8 }}
        {{ include "os2mo.wait-for-mox" . | nindent 8 }}
        - name: create-client-secret
          image: "{{ .Values.keycloak.integrationbuilder.image.repository }}:{{ .Values.keycloak.integrationbuilder.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.integrationbuilder.image.pullPolicy }}
          env:
            {{ include "os2mo.keycloak_terraform_db_connection" .  | nindent 12 }}
            - name: POSTGRES_SCHEMA_NAME
              value: terraform_remote_state_orgviewer_adm

            # Keycloak REST connection
            - name: TF_VAR_admin_password
              valueFrom:
                secretKeyRef:
                  name: {{ include "os2mo.keycloak_admin_secret" . }}
                  key: admin_password

            # Configuration of the client
            - name: TF_VAR_client_name
              value: {{ $keycloak_client_id }}
            - name: TF_VAR_client_roles
              value: '["reader"]'
            - name: TF_VAR_client_secret
              valueFrom:
                secretKeyRef:
                  name: orgviewer-adm-client-secret
                  key: client_secret
          resources:
            {{- toYaml .Values.initContainers.resources | nindent 12 }}
      restartPolicy: Always
{{- end }}
