# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.adguid_sync.enabled }}
{{- $keycloak_client_id := "integration_adguid_sync" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguid-sync
  labels:
    app: adguid-sync
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: adguid-sync
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: adguid-sync
    spec:
      containers:
        - name: adguid-sync
          image: "{{ .Values.adguid_sync.image.registry }}/{{ .Values.adguid_sync.image.repository }}:{{ .Values.adguid_sync.image.tag }}"
          env:
            {{ if .Values.sentry.environment }}
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sentry.secret }}
                  key: dsn
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.sentry.environment | quote }}
            {{ end }}

            {{- if .Values.amqp.amqp_scheme }}
            - name: AMQP_SCHEME
              value: "{{ .Values.amqp.amqp_scheme }}"
            {{- end }}
            - name: AMQP_HOST
              value: "{{ .Values.adguid_sync.amqp_host }}"
            - name: AMQP_USER
              value: "{{ .Values.adguid_sync.amqp_user }}"
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: amqp-secret
                  key: amqp_password
            {{- if .Values.amqp.amqp_port }}
            - name: AMQP_PORT
              value: "{{ .Values.amqp.amqp_port }}"
            {{- end }}
            - name: AMQP_VHOST
              value: "{{ .Values.adguid_sync.amqp_vhost }}"
            - name: MO_URL
              value: "http://mo-service:5000"
            - name: AUTH_SERVER
              value: "http://keycloak-service:8080/auth"
            - name: AUTH_REALM
              value: "mo"
            - name: CLIENT_ID
              value: "{{ $keycloak_client_id }}"
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: adguid-sync-client-secret
                  key: client_secret
            - name: AD_CONTROLLERS
              # The piping to "quote" could give problem as we have seen before with JSON envs
              # If so, use this uncommented line instead and set a default value in values.yaml to '[]'
              # value: "{{ .Values.adguid_sync.ad_controllers }}"
              value: {{ required "AD_CONTROLLERS must be set" .Values.adguid_sync.ad_controllers | quote }}
            - name: AD_DOMAIN
              value: {{ required "AD_DOMAIN must be set" .Values.adguid_sync.ad_domain | quote }}
            - name: AD_USER
              value: {{ required "AD_USER must be set" .Values.adguid_sync.ad_user | quote }}
            - name: AD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: adguid-sync-secret
                  key: ad_password
            - name: AD_CPR_ATTRIBUTE
              value: {{ required "AD_CPR_ATTRIBUTE must be set" .Values.adguid_sync.ad_cpr_attribute | quote }}
            - name: AD_SEARCH_BASE
              value: {{ required "AD_SEARCH_BASE must be set" .Values.adguid_sync.ad_search_base | quote }}
            {{- range $name, $value := .Values.adguid_sync.environment }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - containerPort: 8000
          resources:
            {{- toYaml .Values.adguid_sync.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
            periodSeconds: {{ .Values.adguid_sync.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.adguid_sync.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.adguid_sync.probes.liveness.failureThreshold }}
      initContainers:
        {{ include "os2mo.wait-for-keycloak" . | nindent 8 }}
        - name: create-client-secret
          image: "{{ .Values.keycloak.integrationbuilder.image.registry }}/{{ .Values.keycloak.integrationbuilder.image.repository }}:{{ .Values.keycloak.integrationbuilder.image.tag }}"
          env:
            {{ include "os2mo.keycloak_terraform_db_connection" .  | nindent 12 }}
            - name: POSTGRES_SCHEMA_NAME
              value: terraform_remote_state_adguid_sync

            # Keycloak REST connection
            - name: TF_VAR_admin_password
              valueFrom:
                secretKeyRef:
                  name: {{ include "os2mo.keycloak_admin_secret" . }}
                  key: admin_password

            # Configuration of the client
            - name: TF_VAR_client_name
              value: "{{ $keycloak_client_id }}"
            - name: TF_VAR_client_roles
              value: '["admin"]'
            - name: TF_VAR_client_secret
              valueFrom:
                secretKeyRef:
                  name: adguid-sync-client-secret
                  key: client_secret
            - name: TF_VAR_client_uuid
              value: "ad5711c0-baad-c0de-0000-616467756964"
        {{ include "os2mo.wait-for-mo" . | nindent 8 }}
        - name: os2mo-init
          image: "{{ .Values.os2mo.init.image.registry }}/{{ .Values.os2mo.init.image.repository }}:{{ .Values.os2mo.init.image.tag }}"
          env:
            - name: MO_URL
              value: "http://mo-service:5000"
            - name: AUTH_SERVER
              value: "http://keycloak-service:8080/auth"
            - name: AUTH_REALM
              value: "mo"
            - name: CLIENT_ID
              value: "{{ $keycloak_client_id }}"
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: adguid-sync-client-secret
                  key: client_secret
            - name: LOG_LEVEL
              value: {{ .Values.os2mo.init.log_level | quote }}
          resources:
            {{- toYaml .Values.initContainers.resources | nindent 12 }}
          volumeMounts:
           - name: adguid-sync-init-config-volume
             mountPath: /config
             readOnly: true
      volumes:
        - name: adguid-sync-init-config-volume
          configMap:
            name: adguid-sync-init-config
            items:
              - key: config
                path: config.yml
{{- end }}
