# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
# Annotations to de applied to all resources
annotations:
  chart_repository: "https://git.magenta.dk/rammearkitektur/os2mo-helm-chart"

metrics:
  enabled: false

ingress:
  # Must be 'nginx' for basic-auth to work
  class: "nginx"
  # TLS hostname
  hostname: "os2mo.example.com"
  # Name of the TLS secret to use for ingress. If set TLS will be enabled.
  tls_secret: null
  annotations: {}

wait_for_service:
  image:
    registry: docker.io
    repository: curlimages/curl
    tag: latest

amqp:
  enabled: false
  url_secret: null

os2mo:
  replicaCount: 1
  strategy: Recreate
  image:
    registry: docker.io
    repository: magentaaps/os2mo
    tag: latest
    pullPolicy: IfNotPresent
    pullSecret: null
  port: 80
  gunicorn:
    max_workers: 1
  init:
    enabled: false
    image:
      registry: docker.io
      repository: magentaaps/os2mo-init
      tag: latest
      pullPolicy: IfNotPresent
    config: {}
    log_level: INFO
  resources:
    requests:
      memory: "1024Mi"
      cpu: "500m"
    limits:
      memory: "1536Mi"
      cpu: "1000m"
  headless: false
  external_env_config_map_name: null
  environment: {}
  environment_containing_json: {}
  probes:
    enabled: true
    startupProbe:
      failureThreshold: 150
      periodSeconds: 2
    liveness:
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
    readiness:
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3

  frontend:
    replicaCount: 1
    image:
      registry: docker.io
      repository: magentaaps/os2mo-frontend
      tag: latest
      pullPolicy: IfNotPresent
      pullSecret: null
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    probes:
      startupProbe:
        failureThreshold: 150
        periodSeconds: 2
      liveness:
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3
      readiness:
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3

  naldo:
    image:
      registry: docker.io
      repository: magentaaps/os2mo-naldo
      tag: latest
      pullPolicy: Always
      pullSecret: null
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"

lora:
  replicaCount: 1
  strategy: RollingUpdate
  image:
    registry: docker.io
    repository: magentaaps/lora
    tag: latest
    pullPolicy: IfNotPresent
  gunicorn:
    max_workers: 1
  init:
    image:
      registry: docker.io
      repository: magentaaps/postgres-os2mo
      tag: 12.8-11.7
      pullPolicy: IfNotPresent
    make_superuser: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "250m"
  probes:
    enabled: true
    startupProbe:
      failureThreshold: 150
      periodSeconds: 2
    liveness:
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
    readiness:
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3

dipex:
  image:
    registry: docker.io
    repository: magentaaps/dipex
    tag: latest
    pullPolicy: IfNotPresent
  settings:
    mox.base: "http://mox-service:8080"
    mora.base: "http://mo-service:5000"
    crontab.RUN_IMPORTS_DUMMY: true
    crontab.SVC_USER: "USER@KOMMUNE.NET"
    crontab.SVC_KEYTAB: "/tmp/keytab-file"
    crontab.CRON_BACKUP: "/tmp/backup-dir"
    crontab.CRON_LOG_FILE: "/tmp/cron-log-file"
    crontab.CRON_LOG_JSON_SINK: "/tmp/log.json"
    crontab.BACKUP_SAVE_DAYS: "60"
    crontab.SNAPSHOT_LORA: "/tmp/db-snapshot.sql"
    crontab.OS2MO_COMPOSE_YML: "/tmp/to/os2mo/docker-compose.yml"
  secrets: {}
  resources:
    requests:
      memory: "1000Mi"
      cpu: "250m"
    limits:
      memory: "1500Mi"
      cpu: "1000m"

keycloak:
  image:
    registry: quay.io
    repository: keycloak/keycloak
    tag: 14.0.0
    pullPolicy: IfNotPresent
  init:
    image:
      registry: docker.io
      repository: magentaaps/postgres-keycloak-init
      tag: 12.7-11.7
      pullPolicy: IfNotPresent
  builder:
    image:
      registry: docker.io
      repository: magentaaps/os2mo-keycloak-realm-builder
      tag: latest
      pullPolicy: IfNotPresent
    lora_realm_enabled: false
    lora_dipex_client_enabled: false
    environment: {}
  integrationbuilder:
    image:
      registry: docker.io
      repository: magentaaps/os2mo-keycloak-integration-builder
      tag: latest
      pullPolicy: IfNotPresent
  startupProbe:
    failureThreshold: 60
    periodSeconds: 5
  resources:
    requests:
      memory: "2048Mi"
      cpu: "1000m"
    limits:
      memory: "4096Mi"
      cpu: "2000m"
  # Name of the secret to use to for the admin user password.
  # If not set, the password will be autogenerated.
  admin_secret: null

database:
  # Determine whether to deploy the database as a pod
  external: false
  # Hostname for the database
  image:
    registry: docker.io
    repository: postgres
    tag: "11"
  host: mox-db-service
  user: postgres
  db_prefix: ""
  # Name of the secret to use for external database.
  # If not set, it will be generated with the below password.
  password_secret: null
  # Null means autogenerated password
  password: null
  sslmode: ""
  resources:
    requests:
      memory: "1024Mi"
      cpu: "100m"
    limits:
      memory: "2048Mi"
      cpu: "250m"

omada:
  enabled: false
  image:
    registry: docker.io
    repository: magentaaps/os2mint-omada
    tag: latest
    pullPolicy: IfNotPresent
  odata_url: "MUST BE OVERRIDDEN"
  host_header: null
  ntlm:
    enabled: false
  insecure_skip_ssl_verify: false
  interval: 1800
  cronjob_schedule: "0 6 * * *"
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "250m"

sd_changed_at:
  enabled: false
  init:
    image:
      registry: docker.io
      repository: magentaaps/os2mo-sd-changed-at-init
      tag: master
      pullPolicy: IfNotPresent
  image:
    registry: docker.io
    repository: magentaaps/os2mo-sd-changed-at
    tag: latest
    pullPolicy: IfNotPresent
  mora_base: http://mo-service:5000
  sd_secret_name: sd-secret
  sd_global_from_date: null
  sd_job_function: null
  sd_monthly_hourly_divide: null
  sd_import_run_db: null
  environment: {}
  cronjob_enabled: true
  cronjob_schedule: "*/5 6-17 * * *"
  resources:
    requests:
      memory: "1536Mi"
      cpu: "1000m"
    limits:
      memory: "2048Mi"
      cpu: "2000m"

sdtool:
  enabled: false
  image:
    registry: docker.io
    repository: magentaaps/os2mo-http-trigger-sdtool
    tag: latest
    pullPolicy: IfNotPresent
  sd_secret_name: sd-secret
  sd_too_deep: '[]'
  environment: {}
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "250m"

initContainers:
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"

nameOverride: ""
fullnameOverride: ""

fixture: null

orgviewer:
  image:
    registry: docker.io
    repository: magentaaps/os2orgviewer
    tag: latest
    pullPolicy: IfNotPresent
  environment: {}

  med:
    enabled: false
    replicaCount: 2
    url: null
    org_uuid: null
    title: null
    ingress:
      hostname: null
      tls_secret: null
    resources:
      requests:
        memory: "512Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "250m"

  adm:
    enabled: false
    replicaCount: 2
    url: null
    org_uuid: null
    title: null
    ingress:
      hostname: null
      tls_secret: null
    resources:
      requests:
        memory: "512Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "250m"

os2sync:
  enabled: false
  image:
    registry: docker.io
    repository: os2sync/linux
    tag: latest
    pullPolicy: IfNotPresent
  init:
    image:
      registry: docker.io
      repository: magentaaps/openssl
      tag: latest
      pullPolicy: IfNotPresent
  disable_revocation_check: true
  log_request_response: true
  log_level: DEBUG
  # Note: os2sync specific - not used in the same way as
  # the environment value elsewhere in this chart
  enable_scheduler: true
  environment: PROD
  # Set this to the municipality CVR
  municipality: null
  mysql_version: 8.0.29
  db_host: null
  db_name: os2sync
  db_username: os2sync_admin
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "250m"


orggatekeeper:
  enabled: false
  image:
    registry: docker.io
    repository: magentaaps/os2mo-amqp-trigger-organisation-gatekeeper
    tag: latest
    pullPolicy: IfNotPresent
  environment: {}
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "250m"
  probes:
    startupProbe:
      failureThreshold: 150
      periodSeconds: 2
    liveness:
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
    readiness:
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3


adguid_sync:
  enabled: false
  image:
    registry: docker.io
    repository: magentaaps/os2mo-amqp-trigger-adguid-sync
    tag: latest
    pullPolicy: IfNotPresent
  amqp_scheme: null
  amqp_port: null
  environment: {}
  environment_containing_json: {}
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "250m"
  probes:
    startupProbe:
      failureThreshold: 150
      periodSeconds: 2
    liveness:
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
    readiness:
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
